Рефакторинг пайп функций #14
iassasin/phplate pull request #21
Opened 2017-08-07 19:53 UTC by maestroprog

Отрефакторил #14 
Только переопределение встроенных пайп-функций пока не работает.

2017-08-08 00:56 UTC, iassasin requested changes

2017-08-08 00:56 UTC, iassasin commented on src/Template.php
> +				$globalVars = TemplateEngine::instance()->globalVars;
Ломает возможность присваивания, т.к. будет возвращаться ссылка на переменную из _**копии**_ массива golbalVars.

2017-08-08 00:56 UTC, iassasin commented on src/PipeFunctionsContainer.php
> +	private $options;
Поле нигде не используется

2017-08-08 00:56 UTC, iassasin commented on src/PipeFunctionsContainer.php
> +		} else{
С форматированием в этом и куче подобных мест по всему коду - беда.

2017-08-08 00:56 UTC, iassasin commented on src/TemplateEngine.php
> +class TemplateEngine {
Плохое решение - вынести API в TemplateEngine:
- build теперь означает "построить объект какого-то TemplateEngine", и требует более понятного названия buildTemplate
- Самая часто используемая строка станет слишком длинной, что плохо сказывается на удобстве пользования phplate-ом.

Поэтому:
- Вернуть API в Template
- Вынести виртуальную машину в тот же TemplateEngine или TemplateProgram

2017-08-08 00:56 UTC, iassasin commented on tests/TemplateWidgetTest.php
> +		$res = TemplateEngine::build('template_with_widget', ['hello' => 'Hello', 'world' => 'world']);
Желательно, код самих шаблонов во всех тестах внедрять напрямую в код теста (и использовать ::buildStr), так будет нагляднее. Тем более, что они все-равно в файлах написаны в одну строку.

2017-08-08 05:58 UTC, maestroprog commented on src/Template.php
> +				$globalVars = TemplateEngine::instance()->globalVars;
я это учёл, там где нужно присваивание - используется сам $globalVars

2017-08-08 05:59 UTC, maestroprog commented on src/PipeFunctionsContainer.php
> +	private $options;
упс, вообще я хотел туда опции прокинуть, чтобы не доставать их из инстанса TE

2017-08-08 06:00 UTC, maestroprog commented on src/PipeFunctionsContainer.php
> +		} else{
поправлю, я вроде видел что у тебя после else пробел, а потом скобка :)

2017-08-08 06:14 UTC, maestroprog commented on src/Template.php
> +				$globalVars = TemplateEngine::instance()->globalVars;
а, понял, там чуть ниже идёт return $globalVars по ссылке. поправил это.

2017-08-08 09:42 UTC, iassasin requested changes

2017-08-08 09:42 UTC, iassasin commented on src/TemplateEngine.php
> +	public function build_str($tplStr, array $values): string{
- Сразу бы еще build_str на buildStr поменять, а то единственный выделяется подчеркиванием.
- `string{` - С отступами тут и везде по коду тоже беда

2017-08-08 09:42 UTC, iassasin commented on tests/TemplateTest.php
> +		$this->assertEquals($msg, TemplateEngine::instance()->build('template_test', ['message' => $msg]));
Странное решение O_o

2017-08-08 21:58 UTC, iassasin requested changes

2017-08-08 21:58 UTC, iassasin commented on src/Template.php
> +		return TemplateEngine::init($tplPath, $options ?: new TemplateOptions());
Для чего возвращается объект класса TemplateEngine? Кроме того, если это действительно нужно, документация не обновлена

2017-08-08 21:58 UTC, iassasin commented on src/PipeFunctionsContainer.php
> +	public function eval(string $name, $value, $args){
Не критично, просто почему префикс `eval`? Вроде бы `call` логичнее звучит, или не?

2017-08-08 21:58 UTC, iassasin commented on tests/TemplateWidgetTest.php
> +		$res = Template::build('template_with_widget', ['hello' => 'Hello', 'world' => 'world']);
Опять же, желательно, тестовый код шаблона прямо в код теста вставлять, чтобы было наглядно

2017-08-08 22:57 UTC, iassasin commented on src/PipeFunctionsContainer.php
> +	public function evalSafe($arg): string{
Пробелы тут и далее не расставлены

2017-08-09 21:04 UTC, iassasin approved these changes

2017-08-09 21:08 UTC, merged