Dev cache dir
iassasin/phplate pull request #32
Opened 2017-08-21 20:32 UTC by maestroprog

2017-08-21 23:02 UTC, iassasin requested changes

2017-08-21 23:02 UTC, iassasin commented on src/TemplateEngine.php
> +	public static function instance(): self{
Пробелы убежали =(
Вообще такие стилистические правки вместе с правками кода мешают концентрироваться на функционале, постарайся избегать их и проверять перед пушем в ветки.

2017-08-21 23:02 UTC, iassasin commented on src/TemplateEngine.php
> +		$relative = str_replace(getcwd(), '', $tpath); // получаем путь от корня проекта
- WorkDir не всегда может соответствовать папке с проектом. Далеко не всегда.
- Кроме того, для создания хэша имени следует использовать полный путь к файлу.

2017-08-21 23:02 UTC, iassasin commented on src/TemplateOptions.php
> +		$this->options[self::OPTION_CACHE_DIR] = getcwd();
Аналогично: workdir далеко не всегда является корнем проекта

2017-08-22 05:59 UTC, maestroprog commented on src/TemplateOptions.php
> +		$this->options[self::OPTION_CACHE_DIR] = getcwd();
Изначально было `"./"`, но это не красиво. переделаю на `realpath(".")`.

2017-08-22 05:59 UTC, maestroprog commented on src/TemplateEngine.php
> +		$relative = str_replace(getcwd(), '', $tpath); // получаем путь от корня проекта
> WorkDir не всегда может соответствовать папке с проектом
Да, тут ошибка, там нужен `realpath($path)`, что-то я напутал здесь.
> Кроме того, для создания хэша имени следует использовать полный путь к файлу.
а если проект будет перенесён на "подпуть"? кеш начнет перегенерироваться почём зря.

2017-08-22 06:01 UTC, maestroprog commented on src/TemplateEngine.php
> +	public static function instance(): self{
я на автомате автоформат иногда применяю, и вот...

2017-08-22 10:27 UTC, iassasin requested changes

2017-08-22 10:27 UTC, iassasin commented on docs/options.md
> +* `setCacheDir(string $dir)` позволяет задать папку, в которой будет храниться кэш *Phplate*.
pull-нуть обновления с dev ветки и переписать в соответствии с новым форматом

2017-08-22 10:27 UTC, iassasin commented on src/TemplateEngine.php
> +	public function getOptions(): TemplateOptions{
Тут и далее по прежнему проблемы с отступами

2017-08-22 10:27 UTC, iassasin commented on src/TemplateEngine.php
> +		$relative = substr($tpath, strlen(realpath($this->tplPath))); // получаем относительный путь от папки с шаблонами
Я же говорил, что нужно брать полный, абсолютный путь. Это будет еще более актуальным при реализации #19.

2017-08-22 10:27 UTC, iassasin commented on src/TemplateOptions.php
> +		$this->options[self::OPTION_CACHE_DIR] = realpath('.');
Чем это отличается от getcwd? Все так же используется текущая директория, которая может быть самой разной.

2017-08-23 19:19 UTC, maestroprog commented
Вопрос о директории по умолчанию остаётся открытым.

2017-08-25 14:47 UTC, iassasin approved these changes

2017-08-25 15:01 UTC, merged