#27 Блок else для цикла for
iassasin/phplate pull request #33
Opened 2017-08-21 21:13 UTC by maestroprog

2017-08-21 23:14 UTC, iassasin requested changes

2017-08-21 23:14 UTC, iassasin commented on src/Template.php
> +						$i++;
Можно обойтись без лишней переменной и лишнего инкремента, если вынести первую проверку `$this->readValue($ins[3])` в `if` (и в ветку `else` выполнение блока `else`), а цикл `while` заменить на `do { ... } while`

2017-08-21 23:14 UTC, iassasin commented on src/Template.php
> +					} elseif (isset($ins[4])) {
Следует переделать массив аргументов инструкции так, чтобы он всегда имел константное кол-во элементов для любого случая. Т.е. если тела else нет, записать в элемент 4 null и проверять на него. Это позволит проще расширять функционал инструкции в будущем и вносит меньшую путаницу.

2017-08-21 23:14 UTC, iassasin commented on src/Template.php
> +						$this->execPgm($ins[6]);
Отсутствует проверка на существование тела else

2017-08-21 23:14 UTC, iassasin commented on tests/TemplateTest.php
> +		$tpl = '{? for i in [] 1 else 2 end ?}';
Добавить для наглядности здесь и далее разделитель между лексемой for-а и телом цикла, вот так:
`for i in []; 1 else 2 end`

2017-08-22 00:22 UTC, iassasin commented
Также добавить в комментарии в 218 строчке новые аргументы инструкциям `for` и `fore`

2017-08-22 07:28 UTC, maestroprog commented on src/Template.php
> +						$i++;
Вывернул наизнанку :D

2017-08-22 10:20 UTC, iassasin requested changes

2017-08-22 10:20 UTC, iassasin commented on docs/constructions/for.md
> +else
else не находится внутри блока `{? ?}` и идет на вывод

2017-08-22 10:20 UTC, iassasin commented on src/Template.php
> +					$i = 0;
Ну ты просто издеваешься :laughing: У меня дежавю с вчерашним ревью твоего класса вебсокет-сервера.
Неюзаемая переменная

2017-08-23 16:35 UTC, iassasin approved these changes

2017-08-23 16:36 UTC, merged