#38: Добавил тернарный оператор.
iassasin/phplate pull request #42
Opened 2018-06-21 23:37 UTC by maestroprog

2018-06-21 23:38 UTC, maestroprog commented
Не уверен что такой вариант абсолютно правильный так что прошу ревью.

2018-06-25 19:08 UTC, iassasin commented
Очевидно, неверная реализация. Например, любая из следующих строчек должна сыпать ошибку компиляции, однако успешно компилируется, причем в третьем случае результат еще и не определен (но из-за особенностей реализации выдает false)
```php
Template::buildStr('{{ false ? (1 : 3) }}', []);
Template::buildStr('{{ (false ? 1) : 3 }}', []);
Template::buildStr('{{ false ? 1 }}', []);
```

2018-06-25 19:09 UTC, iassasin requested changes
Реализовывать нужно ручным парсингом оператора в функции `infix()`, наподобие того, как это сделано в `prefix()` с оператором `[`

2018-06-25 19:14 UTC, maestroprog commented
> Реализовывать нужно ручным парсингом оператора в функции infix(), наподобие того, как это сделано в prefix() с оператором [

окей попробую

2018-06-27 08:44 UTC, iassasin commented on src/TemplateLexer.php
> +					$this->error('Expected argument after ":"');
Не аргумент, а expression)

2018-06-27 08:44 UTC, iassasin commented on src/TemplateLexer.php
> +				$a1 = ['?:i', $a1, [$arg1, $arg2]];
В принципе нет смысла во вложенном массиве, достаточно `['?:i', $condition, $then, $else]`

2018-06-27 08:44 UTC, iassasin commented on tests/TemplateLexerTest.php
> +	public function testFailTernary1(){
Не стоит называть функции с номерами в названии, потом их станет 100500, в процессе эволюции десяток из середины удалят и будет путаница с нумерацией. Лучше что-нибудь типа `testFailTernaryIncompleteOperator`

2018-06-27 19:44 UTC, maestroprog commented on tests/TemplateLexerTest.php
> +	public function testFailTernary1(){
Я устану придумывать названия для этих тест-кейсов. Ну и что, что удалят и пропадёт половина номеров, ничего страшного. Все равно последний метод будет - с самым последним номером, если соблюдать порядок добавления тестов.

2018-06-27 19:46 UTC, maestroprog commented on src/TemplateLexer.php
> +					$this->error('Expected argument after ":"');
А я, кстати так и писал, потом перекопипащивал из другого места, где по старому было написано...

2018-06-30 09:13 UTC, iassasin commented
Смержено в https://github.com/iassasin/phplate/commit/7ca736514ade8baacb16b11c2c6e7c37393a6a95

2018-06-30 09:13 UTC, closed without merging